"""add_isAdmin

Revision ID: ff032ffb7a14
Revises: 0925c4a49501
Create Date: 2025-02-22 12:22:01.485268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff032ffb7a14'
down_revision: Union[str, None] = '0925c4a49501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_system_user', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_system_user')
    # ### end Alembic commands ###
